name: "Check-In"

on:
  workflow_dispatch:
  schedule:
    - cron: "40 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install depend
      run: |
        pip install requests
    - name: Start check
      run: |
        python index.py
